/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // --- Existing Brand Colors ---
        brand: {
          green: '#2D7A3A',
          'green-light': '#4CAF50',
          'green-pale': '#E8F5E9',
          red: '#C0392B',
          'red-light': '#E74C3C',
          'red-pale': '#FDECEA',
          'deep-blue': '#1A3A5C',
          'warm-orange': '#E67E22',
          'soft-gold': '#D4AF37',
          cream: '#FEFCF7',
        },
        // --- New Stitch Redesign Colors ---
        "on-primary-fixed": "#00201a",
        "surface": "#fcf9f2",
        "surface-bright": "#fcf9f2",
        "on-secondary-container": "#486a51",
        "on-tertiary-fixed": "#052013",
        "on-secondary-fixed-variant": "#2c4e36",
        "primary": "#003329",
        "on-surface-variant": "#3f4947",
        "on-secondary-fixed": "#00210e",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#1c1c18",
        "primary-container": "#004b3e",
        "outline": "#707977",
        "on-secondary": "#ffffff",
        "tertiary-container": "#2d4839",
        "background": "#fcf9f2",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#aad0b1",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#81d6c0",
        "on-tertiary-container": "#98b6a2",
        "surface-container-high": "#ebe8e1",
        "outline-variant": "#bfc9c6",
        "tertiary-fixed-dim": "#afceb9",
        "inverse-surface": "#31312c",
        "surface-container-low": "#f6f3ec",
        "surface-dim": "#dcdad3",
        "tertiary-fixed": "#cbead5",
        "secondary": "#43664d",
        "on-primary-fixed-variant": "#005143",
        "inverse-primary": "#81d6c0",
        "surface-tint": "#006b59",
        "surface-variant": "#e5e2db",
        "on-primary": "#ffffff",
        "tertiary": "#173123",
        "secondary-container": "#c2e9c9",
        "on-surface": "#1c1c18",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#69bea8",
        "surface-container": "#f0eee7",
        "inverse-on-surface": "#f3f0ea",
        "surface-container-highest": "#e5e2db",
        "primary-fixed": "#9df3dc",
        "on-tertiary-fixed-variant": "#324c3d",
        "on-error": "#ffffff",
        "secondary-fixed": "#c5eccc"
      },
      fontFamily: {
        display: ['var(--font-playfair)', 'Georgia', 'serif'],
        heading: ['var(--font-dm-serif)', 'Georgia', 'serif'],
        body: ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains)', 'monospace'],
        // --- New Stitch Redesign Fonts ---
        "stitch-headline": ["Noto Serif", "serif"],
        "stitch-body": ["Inter", "sans-serif"],
        "stitch-label": ["Manrope", "sans-serif"]
      },
      boxShadow: {
        card: '0 4px 16px rgba(0,0,0,0.08)',
        hover: '0 12px 32px rgba(0,0,0,0.12)',
        premium: '0 20px 60px rgba(45,122,58,0.15)',
        'green-glow': '0 0 40px rgba(45,122,58,0.2)',
      },
      borderRadius: {
        '2xl': '20px',
        '3xl': '28px',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 9s ease-in-out infinite',
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.5s ease-out forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-16px)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      backgroundImage: {
        'green-radial': 'radial-gradient(circle at 30% 20%, rgba(45,122,58,0.08) 0%, transparent 60%)',
        'cream-gradient': 'linear-gradient(135deg, #FEFCF7 0%, #F9FAFB 100%)',
        'hero-gradient': 'linear-gradient(135deg, #F9FAFB 0%, #E8F5E9 50%, #FEFCF7 100%)',
      },
    },
  },
  plugins: [],
};
